os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
# Add remote
  - conan remote add bintray https://api.bintray.com/conan/pepe82sh/test --insert
script:
# Create the package
  - conan create -s compiler=gcc -s compiler.libcxx=libstdc++11 -s compiler.version=7.3 -s arch=armv7 . test/testing
# Call your build system
#  - cmake . -G "Unix Makefiles"
#  - cmake --build .
# Run your tests
#  - ctest .
